version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - USE_SSL=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./script/localstack/s3/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - ${AWS_S3_BUCKET_NAME}.s3.localhost.localstack.cloud
  resource_db:
    container_name: resource_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resource
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5434:5432'
    volumes:
      - ./db-data/resource/:/var/lib/postgresql/data/
      - ./script/resource/sql:/docker-entrypoint-initdb.d/
  songs_db:
    container_name: songs_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=songs
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5435:5432'
    volumes:
      - ./db-data/songs/:/var/lib/postgresql/data/
      - ./script/songs/sql:/docker-entrypoint-initdb.d/
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  resource:
    container_name: resource
    image: microservices/resource-service:v1
    build: '../resource-service/'
    ports:
      - '8082:8080'
    environment:
      - DB_CONNECTION_URL=${RESOURCE_DB_URL}
      - DB_NAME=${RESOURCE_DB_NAME}
      - DB_USERNAME=${RESOURCE_DB_USER}
      - DB_PASSWORD=${RESOURCE_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - AWS_S3_URL=${AWS_S3_URL}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - EUREKA_URI=${EUREKA_URI}
      - RESOURCE_SERVICE_PORT=${RESOURCE_SERVICE_PORT}
    depends_on:
      - localstack
      - broker
      - resource_db
      - service-registry
      - gateway
  songs:
    container_name: songs
    image: microservices/song-service:v1
    build: '../song-service/'
    ports:
      - '8081:8080'
    environment:
      - DB_CONNECTION_URL=${SONGS_DB_URL}
      - DB_NAME=${SONGS_DB_NAME}
      - DB_USERNAME=${SONGS_DB_USER}
      - DB_PASSWORD=${SONGS_DB_PASSWORD}
      - EUREKA_URI=${EUREKA_URI}
      - SONG_SERVICE_PORT=${SONG_SERVICE_PORT}
    depends_on:
      - songs_db
      - service-registry
      - gateway
  processor:
    container_name: processor
    image: microservices/resource-processor:v1
    build: '../resource-processor/'
    ports:
      - '8083:8080'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SONG_SERVICE_URL=${SONG_SERVICE_URL}
      - RESOURCE_SERVICE_URL=${RESOURCE_SERVICE_URL}
      - EUREKA_URI=${EUREKA_URI}
      - RESOURCE_PROCESSOR_PORT=${RESOURCE_PROCESSOR_PORT}
      - CLIENT_SIDE_LOAD_BALANCING=${CLIENT_SIDE_LOAD_BALANCING}
      - GATEWAY_URL=${GATEWAY_URL}
    depends_on:
      - broker
      - service-registry
      - gateway
  service-registry:
    container_name: service-registry
    image: microservices/service-registry:v1
    build: '../service-registry/'
    ports:
      - '8085:8085'
    environment:
      - EUREKA_URI=${EUREKA_URI}
  gateway:
    container_name: gateway
    image: microservices/gateway:v1
    build: '../gateway/'
    ports:
      - '8086:8086'
    environment:
      - EUREKA_URI=${EUREKA_URI}
    depends_on:
      - service-registry