server:
  port: ${GATEWAY_PORT:8086}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: songs
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: resource
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: storage
          uri: lb://storage-service
          predicates:
            - Path=/storages/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}