version: '3.8'

services:
  postgres:
    container_name: songs_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=songs
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./script/sql:/docker-entrypoint-initdb.d/