scrape_configs:
  - job_name: 'microservice-gateway'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: ['host.docker.internal:8086'] ## host and port for your mis