server:
  port: ${STORAGE_SERVICE_PORT:8084}
spring:
  application:
    name: storage-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_CONNECTION_URL:jdbc:postgresql://localhost:5434}/${DB_NAME:storage_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}