server:
    port: 8080
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    datasource:
        url: jdbc:postgresql://localhost:5432/resource
        username: postgres
        password: postgres
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    application:
        name: resource

aws:
    s3:
        url: http://127.0.0.1:4566
        region: eu-central-1
        bucket-name: uploads
        access-key: localstack
        secret-key: localstack